kind: pipeline
name: laravel-drone

steps:
  - name: backend
    image: node
    caches:
      - composer
    commands:
      # - php -v
      # - composer -V
      - cp .env.example .env
      - composer install
      - php artisan key:generate
      # - php artisan migrate
      - ./vendor/bin/phpunit
      