kind: pipeline
name: defaultworkspace:
  base: /php
  path: src/github.com/humamalamin/Simple-CRUD-Laravel5.6:
  - name: test
    image: laravel-drone1
    commands:
      - composer install
      - cp .env.example .env
      - php artisan key:generate
      - php artisan serve
    image: laravel-drone1
    commands:
      - composer install
      - cp .env.example .env
      - php artisan key:generate
      - php artisan serve
    image: laravel-drone1
    commands:
      composer install
      - cp .env.example .env
      - php artisan key:generate
      - php artisan serve