kind: pipeline
name: laravel-drone

steps:
  - name: backend
    image: node
    commands:
      - php -v
      - composer -V
      - cp .env.example .env
      - composer install --prefer-dist
      - php artisan key:generate
      - php artisan migrate
      - ./vendor/bin/phpunit
      