kind: pipeline
name: laravel-drone
# type: docker

steps:
- name: install
  image: composer
  commands:
  - composer install

- name: test
  image: php:7.1.3
  commands:
    - composer -v
    - cp .env.example .env
    - php artisan key:generate
    # - php artisan migrate
    - ./vendor/bin/phpunit

# steps:
#   - name: backend
#     image: node
#     caches:
#       - composer
#     commands:
#       # - php -v
#       # - composer -V
#       - curl -s https://getcomposer.org/installer
#       - mv composer.phar /usr/local/bin/composer
#       - composer -v
#       - cp .env.example .env
#       - composer install
#       - php artisan key:generate
#       # - php artisan migrate
#       - ./vendor/bin/phpunit
      